### ISSUE TITLE
Usage of HC_LIST and docker-arma3-black-company

### ISSUE THREAD

**Issue by Degot** [hasable/docker-arma3-black-company#13]
Hi, I've used your docker image to create Exile server. Everything works perfectly. Thanks.
Question: How to use HC_LIST to create several headless clients with docker?

**Comment by hasable** [comment]
Hi, please in keep in mind that these images are still under development. Actually, I am quite surprise that you were able to use it, as there is a real lack of documentation....

Please find here a sample compose file to run headless client : 
`
version: '2'
services:
  black-company:
    image: "hasable/arma3-black-company:latest"
    container_name: "arma-3-black-company"
    depends_on:
            - mysql
    ports:
            - "2302:2302/udp" 
            - "2303:2303/udp" 
            - "2304:2304/udp"
            - "2305:2305/udp"
            - "2306:2306/udp"
            - "2309:2309/udp"
    environment:
            - EXILE_CONFIG_HOSTNAME=<hostname>
            - EXILE_DATABASE_HOST=mysql
            - EXILE_DATABASE_NAME=<db name>
            - EXILE_DATABASE_USER=<db user>
            - EXILE_DATABASE_PASS=<db password>
            - EXILE_CONFIG_MAXPLAYERS=32
            - EXILE_CONFIG_PASSWORD_ADMIN=<admin password>
            - EXILE_CONFIG_PASSWORD_COMMAND=<command password>
            - EXILE_CONFIG_PASSWORD_RCON=<rcon password>
            - ATK_CONFIG_ADMIN_LIST=<admin steam id list>
            - HC_LIST=hc0
            - CONFIG=/home/steamu/config
    volumes:
            - /opt/black-company/mounts/log:/opt/arma3/@ExileServer/extDB/logs/
            - /opt/black-company/mounts/battleye:/opt/arma3/battleye
    networks:
      armanet:
        aliases:
          - arma-3-bots-master
          - master
    
  arma-3-bots-hc0:
    image: "hasable/arma3-bots"
    container_name: "arma-3-bots-hc0"
    environment:
            - HC_SERVER=master
            - CONFIG=/home/steamu/config
    entrypoint: 
            - /usr/local/bin/docker-entrypoint-hc
    command: "-mod=@Exile;@EBM;@A3XAI;@CBA_A3;@CUPWeapons;@CUPUnits;@CUPVehicles;@R3FArmes;@R3FUnites -name=HC0"
    networks:
      armanet:
        aliases:
          - arma-3-bots-hc0
          - hc0  
          
  mysql:
    image: "mysql/mysql-server:5.7.19-1.1.1"
    container_name: "arma-3-exile-database"
    volumes:
            - /opt/black-company/mysql/lib:/var/lib/mysql
            - /opt/black-company/mysql/log:/var/log
    command: "--sql-mode=ONLY_FULL_GROUP_BY,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    networks:
      armanet:
        aliases:
          - database

networks:
    armanet:  
`

**Comment by Degot** [comment]
Thank you.
